#!/bin/sh

cd /users/nickb/corp-web/mmdev

#clean up the directories for our future use.
/bin/rm built/*
/bin/rm compressed/*

# Compress the JS/CSS/HTML

tools/prepjs *.js
tools/prepcss *.css
tools/prephtml *.html

# Move over the images as txt files
/bin/cp loadimg-data.txt compressed
/bin/cp logo-data.txt compressed
/bin/chmod 644 compressed/loadimg-data.txt
/bin/chmod 644 compressed/logo-data.txt



# finish the HTML files (retrieve to take care of the SSIs and compress)
tools/finishhtml tripplanner.html preferences.html cr.html artisticlicense.html faq.html contact.html geekfaq.html thankyou.html contact.html mailmissing.html mailrecv.html locerror.html locerrorrecev.html

# rename the two files that need to be renamed.
/bin/mv built/tripplanner.html built/index.html
/bin/mv built/preferences.html built/pref.html


# copy the logos over
/bin/cp apple-touch-icon.png built
/bin/chmod 644 built/apple-touch-icon.png
/bin/cp favicon.ico built
/bin/chmod 644 built/favicon.ico

# copy digital forest .htaccess
/bin/cp digitalforest.htaccess built

# copy the robots.txt file
/bin/cp robots.txt built