#!/bin/sh

/usr/local/bin/curl http://www.inmff.net/mmdev/compressed/ |  /users/nickb/bin/javane -jar /users/nickb/bin/htmlcompressor-0.9.3.jar --remove-intertag-spaces --type html > /users/nickb/corp-web/mmdev/built/index.html

/usr/local/bin/curl http://www.inmff.net/mmdev/compressed/preferences.html |  /users/nickb/bin/javane -jar /users/nickb/bin/htmlcompressor-0.9.3.jar --remove-intertag-spaces --type html > /users/nickb/corp-web/mmdev/built/pref.html

/usr/local/bin/curl http://www.inmff.net/mmdev/compressed/cr.html |  /users/nickb/bin/javane -jar /users/nickb/bin/htmlcompressor-0.9.3.jar --remove-intertag-spaces --type html > /users/nickb/corp-web/mmdev/built/cr.html

/usr/local/bin/curl http://www.inmff.net/mmdev/compressed/artisticlicense.html | /users/nickb/bin/javane -jar /users/nickb/bin/htmlcompressor-0.9.3.jar --remove-intertag-spaces --type html > /users/nickb/corp-web/mmdev/built/artisticlicense.html 

/usr/local/bin/curl http://www.inmff.net/mmdev/compressed/abt.html | /users/nickb/bin/javane -jar /users/nickb/bin/htmlcompressor-0.9.3.jar --remove-intertag-spaces --type html > /users/nickb/corp-web/mmdev/built/abt.html

/usr/local/bin/curl http://www.inmff.net/mmdev/compressed/contact.html | /users/nickb/bin/javane -jar /users/nickb/bin/htmlcompressor-0.9.3.jar --remove-intertag-spaces --type html > /users/nickb/corp-web/mmdev/built/contact.html

/usr/local/bin/curl http://www.inmff.net/mmdev/compressed/geekfaq.html | /users/nickb/bin/javane -jar /users/nickb/bin/htmlcompressor-0.9.3.jar --remove-intertag-spaces --type html > /users/nickb/corp-web/mmdev/built/geekfaq.html

/usr/local/bin/curl http://www.inmff.net/mmdev/compressed/thankyou.html | /users/nickb/bin/javane -jar /users/nickb/bin/htmlcompressor-0.9.3.jar --remove-intertag-spaces --type html > /users/nickb/corp-web/mmdev/built/thankyou.html

/usr/local/bin/curl http://www.inmff.net/mmdev/compressed/contact.html | /users/nickb/bin/javane -jar /users/nickb/bin/htmlcompressor-0.9.3.jar --remove-intertag-spaces --type html > /users/nickb/corp-web/mmdev/built/contact.html

/usr/local/bin/curl http://www.inmff.net/mmdev/compressed/mailmissing.html | /users/nickb/bin/javane -jar /users/nickb/bin/htmlcompressor-0.9.3.jar --remove-intertag-spaces --type html > /users/nickb/corp-web/mmdev/built/mailmissing.html

/usr/local/bin/curl http://www.inmff.net/mmdev/compressed/mailrecv.html | /users/nickb/bin/javane -jar /users/nickb/bin/htmlcompressor-0.9.3.jar --remove-intertag-spaces --type html > /users/nickb/corp-web/mmdev/built/mailrecv.html

/bin/chmod 644 /users/nickb/corp-web/mmdev/built/*.html
